### ISSUE TITLE
Remover Falha de segurança

### ISSUE THREAD

**Issue by davidcostadev** [amelco/appedidos-backend#1]
Não pode ter dados de acessos versionados. Para resolver isso a login e senha deverão ser alterados.

Uma alternativa para melhorar isso será usando variáveis de ambiente ou dotenv. 

https://github.com/amelco/appedidos-backend/blob/15681e5344d8efeefe9f30611d2db4c2a2ecfb6f/src/index.js#L14

**Comment by amelco** [comment]
Problema solucionado.

Obrigado pelo feedback.
